name: Setup conan, meson, ninja and gcovr
description: |
  This action installs conan, meson, ninja and gcovr.
  It also installs the default conan configuration and sets the default profile to gcc-9.
  Finally, it caches the conan packages to speed up the build.

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4

    - name: Install conan, meson, ninja and gcovr
      run: pip install conan meson ninja gcovr
      shell: bash

    - name: Install the default conan configuration
      run: conan config install https://github.com/Auterion/conan-config.git
      shell: bash

    - name: Use GCC 9 relwithdebinfo profile as default
      run: ln -sf ~/.conan2/profiles/x86_64-linux-relwithdebinfo-gcc-9 ~/.conan2/profiles/default
      shell: bash

    - name: Use GCC 9 debug as default debug profile
      run: ln -sf ~/.conan2/profiles/x86_64-linux-debug-gcc-9 ~/.conan2/profiles/debug
      shell: bash

    - name: Use Clang 14 relwithdebinfo as clang profile for sanitizers
      run: ln -sf ~/.conan2/profiles/x86_64-linux-relwithdebinfo-clang-14 ~/.conan2/profiles/clang
      shell: bash

    - uses: actions/cache@v3.2.3
      with:
        path: ~/.conan2/p
        key: ${{ github.job }}-${{ hashFiles('./conanfile.py') }}
