default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.6'
    hooks:
      - id: clang-format
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 'v1.3.5'
    hooks:
      - id: clang-tidy
        args: [-p=build/RelWithDebInfo]
      - id: cppcheck
  - repo: https://github.com/Auterion/pre-commit-hooks
    rev: v0.0.1
    hooks:
        - id: commitlint
          stages: [commit-msg]
